name: Keep Bot Awake

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping backend
        run: |
          curl -fsS https://darkinsta.wisp.uno/ || true